var practice = [
  {
    block: "practice",
    condition: "practice_0",
    alt0: "dominating",
    alt1: "dominated",
    p0: 0.75,
    p1: 0.5,
    m0: 2.5,
    m1: 5,
    target: null,
    other: null,
    targetFirst: null,
    presentation: null,
    sequence:
      '{"durations": [3000, 3000, 3000, 3000], "attributes": ["all", "all", "all", "all"], "alternatives": [0, 1, 0, 1]}',
    alt0Pos: "right",
    phase: "practice",
    sequenceKind: "alternatives",
  },
  {
    block: "practice",
    condition: "practice_1",
    alt0: "dominating",
    alt1: "dominated",
    p0: 0.25,
    p1: 0.5,
    m0: 7,
    m1: 3,
    target: null,
    other: null,
    targetFirst: null,
    presentation: null,
    sequence:
      '{"durations": [3000, 3000, 3000, 3000], "attributes": ["p", "m", "p", "m"], "alternatives": ["all", "all", "all", "all"]}',
    alt0Pos: "right",
    phase: "practice",
    sequenceKind: "attributes",
  },
  {
    block: "practice",
    condition: "practice_2",
    alt0: "dominating",
    alt1: "dominated",
    p0: 0.7,
    p1: 0.3,
    m0: 5,
    m1: 3,
    target: null,
    other: null,
    targetFirst: null,
    presentation: null,
    sequence:
      '{"durations": [2000, 2000, 2000, 2000], "attributes": ["all", "all", "all", "all"], "alternatives": [0, 1, 0, 1]}',
    alt0Pos: "left",
    phase: "practice",
    sequenceKind: "alternatives",
  },
  {
    block: "practice",
    condition: "practice_3",
    alt0: "dominating",
    alt1: "dominated",
    p0: 0.7,
    p1: 0.2,
    m0: 4,
    m1: 9,
    target: null,
    other: null,
    targetFirst: null,
    presentation: null,
    sequence:
      '{"durations": [2000, 2000, 2000, 2000], "attributes": ["p", "m", "p", "m"], "alternatives": ["all", "all", "all", "all"]}',
    alt0Pos: "left",
    phase: "practice",
    sequenceKind: "attributes",
  },
  {
    block: "practice",
    condition: "practice_4",
    alt0: "dominating",
    alt1: "dominated",
    p0: 0.75,
    p1: 0.5,
    m0: 2.5,
    m1: 5,
    target: null,
    other: null,
    targetFirst: null,
    presentation: null,
    sequence:
      '{"durations": [1500, 1500, 1500, 1500], "attributes": ["all", "all", "all", "all"], "alternatives": [0, 1, 0, 1]}',
    alt0Pos: "right",
    phase: "practice",
    sequenceKind: "alternatives",
  },
  {
    block: "practice",
    condition: "practice_5",
    alt0: "dominating",
    alt1: "dominated",
    p0: 0.25,
    p1: 0.5,
    m0: 7,
    m1: 3,
    target: null,
    other: null,
    targetFirst: null,
    presentation: null,
    sequence:
      '{"durations": [1500, 1500, 1500, 1500], "attributes": ["p", "m", "p", "m"], "alternatives": ["all", "all", "all", "all"]}',
    alt0Pos: "right",
    phase: "practice",
    sequenceKind: "attributes",
  },
];
